harnessApiVersion: '1.0'
type: PIPELINE
pipelineStages:
- type: ENV_STATE
  name: Simple
  parallel: false
  skipCondition:
    type: DO_NOT_SKIP
  workflowName: Basic - simple
- type: ENV_STATE
  name: 10 nodes
  parallel: false
  skipCondition:
    type: DO_NOT_SKIP
  workflowName: Basic - 10 nodes
- type: ENV_STATE
  name: 10 rolling nodes
  parallel: false
  skipCondition:
    type: DO_NOT_SKIP
  workflowName: Rolling - 10 nodes
